import {
  makeStyles,
  withStyles,
  createStyles,
  Theme,
} from '@material-ui/core/styles'
import { Select, Slider } from '@material-ui/core'

export const useStyles = makeStyles((theme) => ({
  root: {
    maxWidth: 1220,
    margin: '0px auto',
    padding: '50px 0px',
  },
  title: {
    fontSize: 40,
    lineHeight: '120%',
    color: '#fff',
    fontWeight: 800,
  },
  headerContainer: {
    background: '#212121',
    borderRadius: 25,
    marginTop: 53,
    padding: '60px 50px',
  },
  headerContainer2: {
    background: '#212121',
    borderRadius: 25,
    marginTop: 10,
    padding: '60px 50px',
  },
  container: {
    background: '#212121',
    borderRadius: 25,
    marginTop: 53,
    padding: '60px 50px',
    display: 'flex',
  },
  tab: {
    background: '#212121',
    width: '100%',
    boxShadow:
      'inset 2px 4px 4px rgba(0, 0, 0, 0.25), inset 4px 0px 2px rgba(0, 0, 0, 0.25), inset 2px 2px 0px rgba(0, 0, 0, 0.25)',
    borderRadius: 100,
    height: 60,
    marginTop: 60,
    display: 'flex',
  },
  tabItem: {
    width: '100%',
    background: 'tranparent',
    borderRadius: 100,
    color: '#CEBFBF',
    textShadow: '0px 0px 3px rgba(0, 0, 0, 0.8)',
    fontSize: 13,
    fontWeight: 800,
    lineHeight: '18px',
  },
  activeTabItem: {
    width: '100%',
    background: 'linear-gradient(180deg, #493C3C 20.59%, #493C3C 85.35%)',
    borderRadius: 100,
    boxShadow: '0px 4px 2px rgba(0, 0, 0, 0.35)',
    color: '#CEBFBF',
    textShadow: '0px 0px 3px rgba(0, 0, 0, 0.8)',
    fontSize: 13,
    fontWeight: 800,
    lineHeight: '18px',
    marginTop: 3,
    height: 50,
  },
  activeBtn: {
    background: '#57A146',
    color: '#fff',
    borderRadius: 15,
    width: 93,
    marginTop: 20,
  },
  container2: {
    background: '#212121',
    borderRadius: 25,
    marginTop: 53,
    padding: '60px 50px',
  },
  container3: {
    borderRadius: 25,
    border: '3px solid #fff',
    background: '#493C3C',
    padding: '0px 26px 16px 16px',
    marginTop: 28,
    display: 'flex',
    alignItems: 'center',
  },
  h1: {
    color: '#fff',
    fontWeight: 800,
    fontSize: 20,
    lineHeight: '120%',
  },
  h12: {
    color: '#fff',
    fontWeight: 800,
    fontSize: 20,
    lineHeight: '120%',
    marginTop: 53,
  },
  h2: {
    color: '#fff',
    fontWeight: 800,
    fontSize: 30,
    lineHeight: '36px',
  },
  h11: {
    color: '#CEBFBF',
    fontWeight: 800,
    fontSize: 20,
    lineHeight: '120%',
  },
  h22: {
    color: '#CEBFBF',
    fontWeight: 800,
    fontSize: 30,
    lineHeight: '36px',
  },
  h3: {
    color: '#00B929',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '20px',
  },
  h4: {
    fontWeight: 800,
    fontSize: 20,
    lineHeight: '24px',
  },
  h5: {
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '36px',
    fontStyle: 'italic',
  },
  h8: {
    fontWeight: 860,
    fontSize: 20,
    lineHeight: '24px',
    color: '#fff',
    borderBottom: '1px solid #5C5353',
  },
  h9: {
    fontWeight: 860,
    fontSize: 9,
    lineHeight: '24px',
    color: '#fff',
  },
  h91: {
    fontWeight: 860,
    fontSize: 13,
    lineHeight: '120%',
    color: '#fff',
    marginTop: 14,
  },
  h10: {
    fontWeight: 700,
    fontFamily: 'italic',
    fontSize: 9,
    lineHeight: '18px',
    color: '#CEBFBF',
  },
  inputField: {
    marginTop: '30px',
    marginBottom: '10px',
    fontWeight: 800,
    fontSize: '9px',
    boxSizing: 'border-box',
  },
  input: {
    background: 'transparent',
    borderBottom: '2px solid #5C5353',
    color: '#fff',
    fontWeight: 800,
    fontSize: 20,
    lineHeight: '24px',
    border: 'none',
    width: '100%',
    '&:focus-visible': {
      outline: 'none',
    },
  },
  h6: {
    fontSize: 9,
    lineHeight: '10.8px',
    fontWeight: 800,
    color: '#CEC0C0',
    maringTop: 10,
  },
  h7: {
    fontWeight: 800,
    fontSize: 20,
    lineHeight: '120%',
    color: '#fff',
  },
  depositBtn: {
    width: 360,
    background: '#493C3C',
    height: 45,
    borderRadius: 25,
    border: '1px solid transparent',
    fontSize: 13,
    lineHeight: '15.6px',
    fontWeight: 800,
    color: '#fff',
    '&:hover': {
      background: '#493C3C90',
    },
  },
  withdrawBtn: {
    background: 'transparent',
    width: 200,
    height: 45,
    borderRadius: 25,
    border: '1px solid #CEBFBF',
    fontSize: 13,
    marginLeft: 25,
    lineHeight: '15.6px',
    fontWeight: 800,
    color: '#CEBFBF',
  },
}))
