import {
  makeStyles,
  withStyles,
  createStyles,
  Theme,
} from '@material-ui/core/styles'
import { Select, Slider } from '@material-ui/core'

export const useStyles = makeStyles((theme) => ({
  root: {
    maxWidth: 1220,
    margin: '0px auto',
    padding: '50px 0px',
  },
  title: {
    fontSize: 40,
    lineHeight: '120%',
    color: '#fff',
    fontWeight: 800,
  },
  headerContainer: {
    background: '#212121',
    borderRadius: 25,
    marginTop: 53,
    padding: '60px 50px',
  },
  container: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  subConainter1: {
    background: '#212121',
    borderRadius: 25,
    marginTop: 53,
    padding: '60px 50px',
    width: '55%',
  },
  subConainter2: {
    background: '#212121',
    borderRadius: 25,
    marginTop: 53,
    padding: '60px 50px',
    marginLeft: 56,
  },
  swapBtn: {
    borderRadius: 25,
    border: '1px solid #fff',
    background: '#212121',
    width: 92,
    color: '#CEBFBF',
    fontSize: 9,
    fontWeight: 860,
    lineHeight: '120%',
    height: 30,
  },
  saveBtn: {
    background: '#493C3C',
    borderRadius: 25,
    width: 367,
    color: '#fff',
    fontSize: 13,
    lineHeight: '120%',
    fontWeight: 800,
    marginTop: 80,
    padding: '16px 0px',
  },
  tab: {
    background: '#212121',
    width: '100%',
    boxShadow: 'inset 0px 3px 20px rgba(0, 0, 0, 0.15)',
    borderRadius: 100,
    height: 60,
    marginTop: 60,
    display: 'flex',
  },
  tabItem: {
    width: '100%',
    background: 'tranparent',
    borderRadius: 100,
    color: '#CEBFBF',
    textShadow: '0px 0px 3px rgba(0, 0, 0, 0.8)',
    fontSize: 13,
    fontWeight: 800,
    lineHeight: '18px',
  },
  activeTabItem: {
    width: '100%',
    background: 'linear-gradient(180deg, #493C3C 20.59%, #493C3C 85.35%)',
    borderRadius: 100,
    boxShadow: '0px 0px 4px rgba(0, 0, 0, 0.35)',
    color: '#CEBFBF',
    textShadow: '0px 0px 3px rgba(0, 0, 0, 0.8)',
    fontSize: 13,
    fontWeight: 800,
    lineHeight: '18px',
  },
  h1: {
    color: '#fff',
    fontWeight: 800,
    fontSize: 20,
    lineHeight: '120%',
  },
  h2: {
    color: '#fff',
    fontWeight: 800,
    fontSize: 30,
    lineHeight: '36px',
  },
  h3: {
    color: '#00B929',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '20px',
  },
  h4: {
    fontWeight: 800,
    fontSize: 20,
    lineHeight: '24px',
  },
  h5: {
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '20px',
    fontStyle: 'italic',
  },
  h6: {
    fontSize: 9,
    lineHeight: '10.8px',
    fontWeight: 800,
    color: '#CEC0C0',
    maringTop: 10,
  },
  h7: {
    fontWeight: 800,
    fontSize: 20,
    lineHeight: '120%',
    color: '#fff',
  },
}))
